### ISSUE TITLE
Contact form landingpage

### ISSUE THREAD

**Issue by sn3p** [amedeevs/happysmuggler#2]
> M: Dit kan ik nu niet niet doen want dit moet serverside gebeuren, en is ook niet echt mijn cup of tea. Kunnen we Rens voor vragen? Die heeft dit zo voor elkaar denk ik.
> A: mag rens of hepping ook wel ff doen, kan jij dit vragen of moet eric dit ff doen?
> M: Ik stel voor dat Eric dit doet.

**Comment by EricSmuggler** [comment]
Ik heb Hepping al gevraagd, hij wil dat wel even doen.

**Comment by sn3p** [comment]
:+1:

**Comment by sn3p** [comment]
Fixed in https://github.com/amedeevs/happysmuggler/pull/7
